### ISSUE TITLE
Check and improve the Ballerina anti-patterns

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-guides/gcp-microservices-demo#60]
**Description:**
$subject

**Comment by dilanSachi** [comment]
Most of the anti-patterns we found were fixed in the review - https://github.com/ballerina-guides/gcp-microservices-demo/pull/30
We left some error handling scenarios without using `check` to simulate the logging behaviours in the original implementation

**Comment by mohanvive** [comment]
Cases which are identified covered by now.
